name: fokus
description: Mobile application that helps kids with completing tasks while also offering parental control
authors:
    - Stanisław Góra <contact@sgora.dev>
    - Mikołaj Mirko
    - Mateusz Janicki
    - Jan Czubiak
repository: https://github.com/fokus-team/fokus

version: 1.0.0+1

environment:
    sdk: ">=2.6.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter

    mongo_dart:
        git: https://github.com/fokus-team/mongo_dart.git

    firebase_core: ^0.4.0+9
    firebase_analytics: ^5.0.11
    firebase_remote_config: ^0.3.0+3

    bloc: ^4.0.0
    flutter_bloc: ^4.0.0

    equatable: ^1.1.0
    meta: ^1.1.6
    intl: ^0.16.1
    shared_preferences: ^0.5.8

    cupertino_icons: ^0.1.2
    lottie: ^0.4.0+1
    flutter_svg: ^0.17.1
    flutter_markdown: ^0.3.4

dependency_overrides:
    bson:
        git: https://github.com/fokus-team/bson.git
    mongo_dart_query:
        git: https://github.com/fokus-team/mongo_dart_query.git

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_launcher_icons: ^0.7.3

flutter_icons:
    android: true
    ios: false
    image_path: "assets/icon/logo.png"

    adaptive_icon_foreground: "assets/icon/logo_adaptive.png"
    adaptive_icon_background: "assets/icon/bg_adaptive.png"

flutter:
    assets:
        - i18n/pl_PL.json
        - i18n/en_US.json
        - assets/animation/sunflower_with_title.json
        - assets/animation/sunflower_with_title_rotate_only.json
        - assets/image/sunflower_logo.svg
        - assets/image/sunflower_logo.png
        - assets/help/en/first_steps.md
        - assets/help/pl/first_steps.md

    fonts:
        - family: Lato
          fonts:
            - asset: assets/font/lato/Lato-Bold.ttf
              style: normal
              weight: 700
            - asset: assets/font/lato/Lato-BoldItalic.ttf
              style: italic
              weight: 700
            - asset: assets/font/lato/Lato-Regular.ttf
              style: normal
              weight: 400
            - asset: assets/font/lato/Lato-Italic.ttf
              style: italic
              weight: 400
            - asset: assets/font/lato/Lato-Light.ttf
              style: normal
              weight: 300
            - asset: assets/font/lato/Lato-LightItalic.ttf
              style: italic
              weight: 300

    uses-material-design: true
