name: fokus
description: Mobile application that helps kids complete their daily tasks under parental control
authors:
    - Stanisław Góra <contact@sgora.dev>
    - Mikołaj Mirko
    - Mateusz Janicki
    - Jan Czubiak
repository: https://github.com/fokus-team/fokus

version: 0.1.0-dev

environment:
    sdk: ">=2.6.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter

    mongo_dart:
        git: https://github.com/fokus-team/mongo_dart.git

    firebase_core: ^0.4.0+9
    firebase_analytics: ^5.0.11
    firebase_crashlytics: ^0.1.4+1
    firebase_remote_config: ^0.3.0+3
    firebase_auth: ^0.16.1
    flutter_auth_buttons: ^0.9.0
    google_sign_in: ^4.5.1

    get_it: ^4.0.2
    bloc: ^6.0.1
    flutter_bloc: ^6.0.1

    equatable: ^1.1.0
    meta: ^1.1.6
    date_utils: ^0.1.0+3
    logging: ^0.11.4
    intl: ^0.16.1
    formz: ^0.3.0
    shared_preferences: ^0.5.8

    cupertino_icons: ^0.1.2
    lottie: ^0.4.0+1
    flutter_svg: ^0.18.0
    flutter_markdown: ^0.3.4
    smart_select: ^3.0.3
    badges: ^1.1.1
    implicitly_animated_reorderable_list: ^0.2.3
    flutter_picker: ^1.1.5
    table_calendar: ^2.2.3

dependency_overrides:
    bson:
        git: https://github.com/fokus-team/bson.git
    mongo_dart_query:
        git: https://github.com/fokus-team/mongo_dart_query.git

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_launcher_icons: ^0.7.3

flutter_icons:
    android: true
    ios: false
    image_path: "assets/icon/logo.png"

    adaptive_icon_foreground: "assets/icon/logo_adaptive.png"
    adaptive_icon_background: "assets/icon/bg_adaptive.png"

flutter:
    assets:
        - i18n/pl_PL.json
        - i18n/en_US.json
        - assets/animation/sunflower_with_title.json
        - assets/animation/sunflower_with_title_rotate_only.json
        - assets/image/sunflower_logo.svg
        - assets/image/sunflower_logo.png
        - assets/help/en/
        - assets/help/pl/
        - assets/image/avatar/
        - assets/image/avatar/child/
        - assets/image/award/
        - assets/image/award_level/
        - assets/image/badge/
        - assets/image/currency/

    fonts:
        - family: Lato
          fonts:
            - asset: assets/font/lato/Lato-Bold.ttf
              style: normal
              weight: 700
            - asset: assets/font/lato/Lato-BoldItalic.ttf
              style: italic
              weight: 700
            - asset: assets/font/lato/Lato-Regular.ttf
              style: normal
              weight: 400
            - asset: assets/font/lato/Lato-Italic.ttf
              style: italic
              weight: 400
            - asset: assets/font/lato/Lato-Light.ttf
              style: normal
              weight: 300
            - asset: assets/font/lato/Lato-LightItalic.ttf
              style: italic
              weight: 300

    uses-material-design: true
